services:
  - type: web
    name: jx3-blog
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:NpQ-gEw8jLPL44A@db.fanffwnhkxpfhttylntw.supabase.co:5432/postgres
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: JX3_ADMIN_2026
